name: Python application test with Github Actions

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: test with pytest
      run: coverage run -m pytest 
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    
